name: promptr
description: A simple and extensible Dart package for creating interactive command-line interfaces. Includes support for text input, confirmations, and menu-style selections—ideal for building robust CLI tools.
version: 1.0.0
repository: https://github.com/imshibl/promptr.git

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  charcode: ^1.4.0
  io: ^1.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
